myapp/urls.py
from django.urls import path
from myapp import views
app_name = 'myapp'

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.home, name = "home"),
    path('history/', views.history, name = "history"),
    path('foods/', views.foods, name = "foods"),
    path('places/', views.places, name = "places"),


]   

template_inheritance/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls")),  
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, "home.html")

def history(request):
    return render(request, "history.html")

def foods(request):
    return render(request, "foods.html")

def places(request):
    print(request.POST)
    return render(request, "places.html")

templates/foods.html
{% extends "home.html" %}

{% load static %}

{% block title %}
    <title>Popular Foods </title>
{% endblock %}


{% block body_block %}

<section class="jumbotron text-center">
	<div class="container">
		<h1>Popular Foods</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
</section> 
<!-- 
<div class="">
    <a href="history.html"><img src="{% static 'images/foods/1.jpg' %}" alt="image not found" height="324px" width="324px"></a>
    <img src="{% static 'images/foods/2.jpg' %}" alt="image not found" height="324px" width="324px">
    <img src="{% static 'images/foods/3.webp' %}" alt="image not found" height="324px" width="324px">
    <img src="{% static 'images/foods/gur-pitha.jpg' %}" alt="image not found" height="324px" width="324px">
    <img src="{% static 'images/foods/guur-pitha.jpg' %}" alt="image not found" height="324px" width="324px">
    <img src="{% static 'images/foods/hqdefault.jpg' %}" alt="image not found" height="324px" width="324px">
    <img src="{% static 'images/foods/jalebi.jpg' %}" alt="image not found" height="324px" width="324px">

</div> -->


<!-- gallary image  -->
<img src="{% static 'images/foods/2.jpg' %}" height="324px" width="324px" data-toggle="modal" data-target=".bd-example-modal-lg">
<!--End gallary image  -->

<!-- modal image with description -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <!-- modal header  -->
      <div class="modal-header">     
      <h4>Motichur laddu</h4> 
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <!-- End modal header  -->
          <img src="{% static 'images/foods/2.jpg' %}" class="a" align="center" alt="image not found" height="324px" width="324px">

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
         tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
         quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
         consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
         cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
         proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
         <!-- <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button> -->
         <!-- modal footer  -->
         <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
      </div>
      <!-- End modal footer  -->

    </div>
  </div>
</div>
<!--End modal image with description -->


<!-- ================================================================================== -->


<!-- gallary image  -->
<img src="{% static 'images/foods/1.jpg' %}" height="324px" width="324px" data-toggle="modal" data-target=".bd-example-modal-lg">
<!--End gallary image  -->

<!-- modal image with description -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <!-- modal header  -->
      <div class="modal-header">     
      <h4>Motichur laddu</h4> 
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <!-- End modal header  -->
          <img src="{% static 'images/foods/.jpg' %}" class="a" align="center" alt="image not found" height="324px" width="324px">

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
         tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
         quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
         consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
         cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
         proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
         <!-- <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button> -->
         <!-- modal footer  -->
         <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
      </div>
      <!-- End modal footer  -->

    </div>
  </div>
</div>
<!--End modal image with description -->


<!-- ================================================================================== -->


<!-- gallary image  -->
<img src="{% static 'images/foods/hqdefault.jpg' %}" height="324px" width="324px" data-toggle="modal" data-target=".bd-example-modal-lg">
<!--End gallary image  -->

<!-- modal image with description -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <!-- modal header  -->
      <div class="modal-header">     
      <h4>Motichur laddu</h4> 
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <!-- End modal header  -->
          <img src="{% static 'images/foods/hqdefault.jpg' %}" class="a" align="center" alt="image not found" height="324px" width="324px">

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
         tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
         quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
         consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
         cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
         proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
         <!-- <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button> -->
         <!-- modal footer  -->
         <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
      </div>
      <!-- End modal footer  -->

    </div>
  </div>
</div>
<!--End modal image with description -->



<!-- ================================================================================== -->


<!-- gallary image  -->
<img src="{% static 'images/foods/jalebi.jpg' %}" height="324px" width="324px" data-toggle="modal" data-target=".bd-example-modal-lg">
<!--End gallary image  -->

<!-- modal image with description -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <!-- modal header  -->
      <div class="modal-header">     
      <h4>Motichur laddu</h4> 
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <!-- End modal header  -->
          <img src="{% static 'images/foods/jalebi.jpg' %}" class="a" align="center" alt="image not found" height="324px" width="324px">

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
         tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
         quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
         consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
         cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
         proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
         <!-- <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button> -->
         <!-- modal footer  -->
         <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
      </div>
      <!-- End modal footer  -->

    </div>
  </div>
</div>
<!--End modal image with description -->


{% endblock body_block %}

templates/history.html
{% extends "home.html" %}
{% load static %}

{% block title %}
    <title>History | Purulia </title> 
{% endblock %}

{% block body_block %}

<section class="jumbotron text-center">
	<div class="container">
		<h1>History of Purulia</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
</section>  

<div class="container" align="center">
	<img src="{% static 'images/history/purulia.jpg' %}">
</div>

<div class="container">
    <h3><ul>History</ul></h3>
    <p>The territory of present Purulia district was a part of Banga, one of the 16 Mahajanapadas according to 
        Jaina Bhagavati Sutra (c. 5th century CE) and was also a part of the country known as Vajra-bhumi in 
        ancient period.[2][3][4] During medieval period, this territory was regarded as part of Jharkhand 
        region. Little is known about Purulia before the British East India Company acquired this territory 
        by obtaining the grant of Diwani of the subahs of Bengal, Bihar, Odisha in 1765.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
</div>

{% endblock body_block %}

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    <title>Purulia | Home Page</title>
    {% endblock %}
    <!-- custom css  -->
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}">     -->
    <!-- bootstrap css  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" >
    <!-- bootstrap js  -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script> 
    <style>
    .a {
        display: block;
        margin-left: auto;
        margin-right: auto;
        }
    </style>
</head>
<body>
    <!-- <h1 align="center" style="color:#11283e" style="font-family:inherit">PURULIA</h1> -->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #00002E;">
        <a class="navbar-brand" href="#">
          <h3>PURULIA</h3>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <!-- <div class="collapse navbar-collapse"> -->
              <!-- <ul class="nav-item"> -->
              <li><a class="nav-link active" href="{% url 'myapp:home' %}">Home</a></li>
              <li><a class="nav-link" href="{% url 'myapp:history' %}">History</a></li>
              <li><a class="nav-link" href="{% url 'myapp:foods' %}">Foods</a></li>
              <li><a class="nav-link" href="{% url 'myapp:places' %}">Places</a></li> 
            <!-- </ul> -->
            <!-- </div> -->
          </div>
        </div>
      </nav>

      {% block body_block %}

      <!-- carousel  -->
      

      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'images/birdfly1.jpg' %}" class="d-block w-100" alt="chou">
            <div class="carousel-caption">
                    <h4>Second Thumbnail label</h4>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/akash1.jpg' %}" class="d-block w-100" alt="durga">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/boat1.jpg' %}" class="d-block w-100" alt="mukhos">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/ilp1.jpg' %}" class="d-block w-100" alt="mukhos">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
     
      <!-- End carousel  -->

      <section class="jumbotron text-center">
        <div class="container">
          <h1>Welcome to Purulia</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
      </section>  
      <div>
        <!-- <img src="{% static 'images/chou.jpg' %}" alt="image not found" height="580px" width="1333px"> -->
      </div> 
      {% endblock body_block %}

      

</body>
</html>

templates/places.html
{% extends "home.html" %}
{% load static %}

{% block title %}
    <title> Tourist Places </title>
{% endblock %}

{% block body_block %}
  <section class="jumbotron text-center">
  <div class="container">
    <h1>Tourist Places</h1>
    <h5>Purulia district is one of the twenty three districts of West Bengal state in Eastern India. Purulia is the administrative headquarters of the district. Some of the other important towns of Purulia district are Raghunathpur-Adra, Jhalida and Balarampur. </h5>
  </div>
</section> 



  <!-- <div class="container">
    <form method="POST">
      {% csrf_token %}
      <label for="Firstname"> <strong>FIRSTNAME</strong> :
        <input type="text" name="firstname" id="fname">
        <input class="btn btn-primary" type="submit" value="Submit">
      </label>
    </form>
  </div> -->

<!-- <div>
    <img src="{% static 'images/places/monsoon.jpg' %}" alt="image not found" height="324px" width="324px">
    <img src="{% static 'images/places/panchokot.jpg' %}" alt="image not found" height="324px" width="324px">
    <img src="{% static 'images/places/AyodhyaHills.jpg' %}" alt="image not found" height="324px" width="324px">
    <img src="{% static 'images/places/monsoon.jpg' %}" alt="image not found" height="324px" width="324px">
    <img src="{% static 'images/places/panchokot.jpg' %}" alt="image not found" height="324px" width="324px">
    <img src="{% static 'images/places/AyodhyaHills.jpg' %}" alt="image not found" height="324px" width="324px">

</div> -->


<!-- gallary image  -->
<img src="{% static 'images/places/panchokot.jpg' %}" height="324px" width="324px" id="modal-window-one" data-toggle="modal" data-target=".bd-example-modal-lg">
<!--End gallary image  -->

<!-- modal image with description -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" id="modal">
    <div class="modal-content">
      <!-- modal header  -->
      <div class="modal-header">     
      <h4>Garh Panchokot</h4> 
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <!-- End modal header  -->
          <img src="{% static 'images/places/panchokot.jpg' %}" class="a"  alt="image not found" height="324px" width="324px">

          <h6>Garh Panchkot is a ruined fort located in the eastern part of India at the foothills of Panchet Hill in the district of Purulia, West Bengal. The ruins of the Panchkot Palace are a silent testimony to the Bargi attack during the 18th century.  
              In the fort's construction a combination of natural and man made resources were used to build it.

          A semicircular moat was built which started from one end of the foothill to the other end. The only way to enter was by crossing the moat by using a boat at the centre of the semicircle. The rest of the area was either inaccessible due to large growth of a special type of bamboo tree which grew thick wild making it very difficult for intruders as well as a thick and high stone wall that was constructed.

          600 feet above in the middle of the Panchakot Hill were the guard's quarters. In contrast to the architecture of the palace below, it was completely made of large stone slabs.

          The guard's quarter has a strategic position. Spread over a 500 square meters area is more of a miniature fort surrounded by solid rock walls with only one entry point, the pyramid like hollow gate from where the entire palace below and the surroundings could be watched. </h6>
         <!-- <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button> -->
         <!-- modal footer  -->
         <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
      </div>
      <!-- End modal footer  -->

    </div>
  </div>
</div>
<!--End modal image with description -->


<!-- ========================================================================================= -->



<!-- gallary image  -->
<img src="{% static 'images/places/monsoon.jpg' %}" height="324px" width="324px" id="modal-window-two" data-toggle="modal" data-target=".bd-example-modal-lg">
<!--End gallary image  -->

<!-- modal image with description -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" data-modal="modal-window-two" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <!-- modal header  -->
      <div class="modal-header">     
      <h4>Garh Panchokot</h4> 
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <!-- End modal header  -->
          <img src="{% static 'images/places/monsoon.jpg' %}" class="a"  alt="image not found" height="324px" width="324px">

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
         tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
         quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
         consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
         cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
         proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
         <!-- <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button> -->
         <!-- modal footer  -->
         <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
      </div>
      <!-- End modal footer  -->

    </div>
  </div>
</div>
<!--End modal image with description -->



<!-- ========================================================================================= -->



<!-- gallary image  -->
<img src="{% static 'images/places/AyodhyaHills.jpg' %}" height="324px" width="324px" data-toggle="modal" data-target=".bd-example-modal-lg">
<!--End gallary image  -->

<!-- modal image with description -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <!-- modal header  -->
      <div class="modal-header">     
      <h4>Garh Panchokot</h4> 
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <!-- End modal header  -->
          <img src="{% static 'images/places/AyodhyaHills.jpg' %}" class="a"  alt="image not found" height="324px" width="324px">

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
         tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
         quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
         consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
         cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
         proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
         <!-- <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button> -->
         <!-- modal footer  -->
         <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
      </div>
      <!-- End modal footer  -->

    </div>
  </div>
</div>
<!--End modal image with description -->



<!-- ========================================================================================= -->



<!-- gallary image  -->
<img src="{% static 'images/places/AyodhyaHills.jpg' %}" height="324px" width="324px" data-toggle="modal" data-target=".bd-example-modal-lg">
<!--End gallary image  -->

<!-- modal image with description -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <!-- modal header  -->
      <div class="modal-header">     
      <h4>Garh Panchokot</h4> 
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <!-- End modal header  -->
          <img src="{% static 'images/places/AyodhyaHills.jpg' %}" class="a"  alt="image not found" height="324px" width="324px">

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
         tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
         quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
         consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
         cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
         proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
         <!-- <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button> -->
         <!-- modal footer  -->
         <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
      </div>
      <!-- End modal footer  -->

    </div>
  </div>
</div>
<!--End modal image with description -->






{% endblock body_block %}